<html>
<head>
    <meta charset="UTF-8">
    <style></style>
</head>

<body>

<div>
    <h1 style="text-align: center;">
        TERM OF USE
    </h1>

    Before using KV INCOME or creating a KV INCOME account ("Account"), please carefully read the following Terms of Service to understand your rights and legal obligations with respect to KV INCOME Co., Ltd. The "Service" we provide or make available includes (a) KV INCOME, (b) services provided by KV INCOME and by KV INCOME's customer software available on KV INCOME, and (c) all information, links, features, data, text, images, messages, content, programs. Any new features added or expanded to the Service are within the scope of these Terms of Service. These Terms of Service govern your use of the Service provided by KV INCOME.
    1.2 Before becoming a User of KV INCOME, you need to read and accept all the terms and conditions set forth in, and referred to, these Terms of Service and the Privacy Policy referred to herein.
    1.3 KV INCOME reserves the right to change, modify, suspend, or terminate all or any part of KV INCOME or the Service at any time in accordance with applicable law. The Trial Version of the Service or the feature of the Service may not be identical to the final version.
    1.4 KV INCOME reserves the right to refuse requests to open an Account or your access to KV INCOME or the Service in accordance with applicable law and the terms of service. BY USING THE SERVICE OR CREATING AN ACCOUNT AT KV INCOME, YOU HAVE ACCEPTED AND AGREED TO THESE TERMS OF SERVICE AND THE REFERENCED SUPPLEMENTAL POLICIES. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, PLEASE DO NOT USE THE SERVICE OR ACCESS KV INCOME. IF YOU ARE A MINOR OR HAVE LIMITED LEGAL CAPACITY TO ACT UNDER APPLICABLE LAW IN THE COUNTRY YOU RESIDE IN, YOU NEED TO RECEIVE SUPPORT OR APPROVAL FROM YOUR PARENTS OR LEGAL GUARDIAN, AS APPLICABLE, TO OPEN AN ACCOUNT OR USE THE SERVICE. IN SUCH CASE, YOUR PARENTS OR LEGAL GUARDIAN, AS APPLICABLE, NEED TO PROVIDE ASSISTANCE FOR YOU TO UNDERSTAND OR ACCEPT THE TERMS OF THIS SERVICE AGREEMENT. IF YOU ARE NOT SURE ABOUT YOUR AGE OR LEGAL CAPACITY TO ACT, OR DO NOT UNDERSTAND THESE TERMS OR THE RELEVANT APPLICABLE LAWS REGARDING AGE OR LEGAL CAPACITY TO ACT, PLEASE DO NOT CREATE AN ACCOUNT OR USE THE SERVICE UNTIL YOU RECEIVE ASSISTANCE FROM YOUR PARENTS OR LEGAL GUARDIAN. IF YOU ARE THE PARENT OR LEGAL GUARDIAN OF A MINOR OR PERSON WITH LIMITED LEGAL CAPACITY TO ACT, AS APPLICABLE UNDER APPLICABLE LAW, YOU NEED TO PROVIDE SUPPORT FOR THE WARD TO UNDERSTAND OR HAVE THE REPRESENTATIVE OF THE WARD ACCEPT THESE TERMS OF SERVICE AND BE RESPONSIBLE FOR THE ENTIRE PROCESS OF USING THE ACCOUNT OR SERVICES OF KV INCOME WHETHER OR NOT THE ACCOUNT HAS BEEN OR WILL BE CREATED.
    2.	PRIVACY RIGHTS 2.1 KV INCOME values the protection of your information. To protect the rights of users, KV INCOME provides the Privacy Policy on KV INCOME.vn to explain in detail the security activities of KV INCOME. Please refer to the Privacy Policy to understand how KV INCOME collects and uses information related to the Account and/or the use of the User ("User Information"). These Terms of Service are closely related to the Privacy Policy. By using the Service or providing information on KV INCOME, the User:
    a. You allow KV INCOME to collect, use, disclose, and/or process the Content, your personal data, and User Information as provided in the Privacy Policy;
    b. You agree and acknowledge that the information provided on KV INCOME will be jointly owned by you and KV INCOME.
    c. We will not, directly or indirectly, disclose User Information to any third party, or in any way allow any third party to access or use your User Information.
    2.2 In the event that a User owns personal data of another User through the use of the Service ("Information Recipient") hereby agrees that they will (i) comply with all applicable laws regarding the protection of personal information relating to such information; (ii) allow the User who is the owner of the personal information that the Information Recipient has collected ("Information Discloser") to delete their information collected from the Information Recipient's database; and (iii) allow the Information Discloser to review the information collected about them by the Information Recipient, in accordance with or as required by current applicable laws and regulations.
    3.	LIMITATION OF LIABILITY
    3.1 KV INCOME grants the User the appropriate rights to access and use the Services under the terms and conditions set forth in these Terms of Service. All Content, trademarks, service marks, trade names, logos, and other exclusive intellectual property assets ("Intellectual Property Assets") displayed on KV INCOME are owned by KV INCOME and third-party owners, if any. No party accessing KV INCOME is granted the right or license, directly or indirectly, to use or copy any Intellectual Property Assets, nor is any party accessing KV INCOME entitled to claim any rights, ownership, or interest in relation to the Intellectual Property Assets. By using or accessing the Services, you agree to comply with the copyright, trademark, service mark, or any other laws protecting the Services, KV INCOME, and the Content of KV INCOME. You agree not to copy, distribute, reproduce, transfer, publicly disclose, publicly perform, modify, adapt, rent, sell, or create derivative works of any part of the Services, KV INCOME, and the Content of KV INCOME. You may not replicate or modify any portion or the entirety of KV INCOME's content on any server or as part of any other website without the prior written consent of KV INCOME. Additionally, you agree that you will not use any robot, spider program, or any automatic or manual method to monitor or copy the Content of KV INCOME without the prior written consent of KV INCOME (this consent applies to basic search tools on search websites that directly connect users to that website).
    3.2 KV INCOME allows connections from User's websites to KV INCOME, provided that the User's website is not understood as any confirmation or affiliation with KV INCOME.
    4.	SOFTWARE Any software provided by KV INCOME to the User is subject to the scope of these Terms of Service. KV INCOME reserves all rights related to software not expressly granted by KV INCOME herein. Any scripts or code, linked to or referenced from the Service, are licensed to you by third parties who are the owners of that script or code, not by KV INCOME.


    5.	ACCOUNT AND SECURITY 5.1 Some features of our Service require you to register an Account by choosing a unique username ("Username") and password while providing certain personal information. You may use your Account to access other products, websites, or services allowed by KV INCOME, whether they have a connection or are in collaboration. KV INCOME does not verify and is not responsible for any content, features, security, services, privacy policies, or other practices of those products, websites, or services. In case you use your Account to access other products, websites, or services allowed by KV INCOME, whether they have a connection or are in collaboration, the terms of service of those products, websites, or services, including their corresponding privacy policies, still apply when you use those products, websites, or services, even if those terms of service differ from the Terms of Service and/or Privacy Policy of KV INCOME.
    5.2 You agree to (a) keep your password confidential and only use the Username and password when logging in, (b) ensure that you log out of your account after each session on KV INCOME, and (c) immediately notify KV INCOME if you discover any unauthorized use of your Account, Username, and/or password. You are responsible for activities under your Username and Account, including losses or damages arising from unauthorized use related to the password or from non-compliance with these User Terms.
    5.3 You agree that KV INCOME has the right to immediately delete the Account and Username of the User, remove or delete from KV INCOME any Content related to the Account and Username of the User for any reason with or without notice or liability to the User or any third party. The basis for taking these actions may include (a) the Account and Username being inactive for an extended period, (b) violation of the terms or spirit of these Terms of Service, (c) engaging in illegal, fraudulent, harassing, invasive, threatening, or abusive behavior, (d) having multiple different user accounts, (e) purchasing products on KV INCOME for business purposes, (f) making large quantity purchases from a Seller or a group of related Sellers, (g) abusing discount codes or sponsorships or promotional benefits (including selling discount codes to third parties as well as abusing discount codes on KV INCOME), (h) engaging in behavior harmful to other Users, third parties, or the economic interests of KV INCOME. The use of the Account for illegal, fraudulent, harassing, invasive, threatening, or abusive purposes may be reported to the relevant authorities in accordance with applicable laws.
    5.4 Users may request the deletion of their account by notifying KV INCOME in writing (here). However, Users are still responsible and liable for any incomplete transactions (occurring before or after the account is deleted) or the transportation of goods related to the requested deletion of the account. In that case, according to the Terms of Service, Users must contact KV INCOME after promptly and thoroughly performing and completing any pending transactions. Users are responsible for their account deletion requests.
    5.5 You may only use the Service and/or open an Account at KV INCOME if you meet all the conditions to accept these Terms of Service.
    6.	TERMS OF USE 6.1 The right to use KV INCOME and the Service is valid until terminated. The right to use may be terminated according to these Terms of Service or in the event that the User violates any terms or conditions set forth in these Terms of Service. In that case, KV INCOME may terminate the User's use with or without notice.
    7.    6.2 Users are not allowed to:
    8.    (a) upload, post, transmit, or otherwise publicly disclose any unlawful, harmful, threatening, abusive, harassing, disturbing, alarming, deceptive, defamatory, offensive, pornographic, obscene, privacy-infringing, hateful, or racially, ethnically, or otherwise inappropriate content;
    9.    (b) violate the law, the rights of third parties, or KV INCOME's Prohibited/Restricted Product Policy;
    10. (c) publish, transmit, or in any other form display any content that involves minors or uses the Service to harm minors in any way;
    11. (d) use the Service or post Content to impersonate any individual or organization, or in any other way distort individuals or organizations;
    12. (e) falsify headers or otherwise manipulate formats to conceal the origin of any Content transmitted through the Service;
    13. (f) remove any proprietary notices from KV INCOME;
    14. (g) cause, allow, or authorize the modification, creation of derivative works, or adaptation of the Service without explicit permission from KV INCOME;
    15. (h) use the Service for the benefit of any third party or engage in any behavior not accepted under these Terms of Service;
    16. 6.3 Users understand that Content, whether publicly posted or privately transmitted, is the sole responsibility of the person who created that Content. This means that you, not KV INCOME, are entirely responsible for any Content you upload, post, email, transmit, or otherwise publicly disclose on KV INCOME. Users understand that by using KV INCOME, they may encounter Content that they find offensive, inappropriate, or objectionable. KV INCOME will not be liable for Content, including errors or omissions related to Content, or for any loss or damage arising from the use of, or reliance on, Content posted, emailed, transmitted, or otherwise made available through KV INCOME.
    17. 6.4 Users acknowledge that KV INCOME and its designated parties have the right (but not the obligation) to screen, refuse, delete, suspend, pause, remove, or relocate any Content available on KV INCOME, including any Content or information you have posted. KV INCOME has the right to remove Content that (i) violates the Terms of Service, (ii) is subject to valid complaints under applicable law from other Users, (iii) is subject to valid notices of intellectual property infringement or legal demands for removal, or (iv) for other reasons under applicable law. KV INCOME has the right to block communications (including status updates, postings, messages, and/or chats) about or related to the Service as part of our efforts to protect the Service or Users of KV INCOME, or otherwise enforce the terms of these Terms of Service. Users agree that they must evaluate and bear all risks associated with the use of any Content, including any reliance on the accuracy, completeness, or usefulness of that Content. In this regard, Users acknowledge that they do not have to and, to the maximum extent permitted by law, should not rely on any Content created by KV INCOME or submitted to KV INCOME, including information on KV INCOME Forums or other parts of KV INCOME.
    18. 6.5 Users agree and consent that KV INCOME may access, maintain, and disclose User Account information when required by law or court order, or at the request of a court or government agency or authorized government authority, or for other reasons under applicable law: (a) to comply with legal procedures; (b) to enforce the Terms of Service; (c) to respond to complaints regarding Content that infringes the rights of third parties; (d) to respond to User requests related to customer care; or (e) to protect the rights, property, or safety of KV INCOME
    7.    VIOLATION OF TERMS OF SERVICE 7.1 Violation of this policy may result in various actions, including any or all of the following:
    ·         Limiting the use of the Account;
    ·         Suspending and terminating the Account;
    ·         Criminal charges;
    ·         Imposing civil measures, including claims for damages and/or applying temporary emergency measures;
    ·         Other actions or sanctions according to Community Standards, Operating Regulations, or KV INCOME Policies.
    7.2 If you discover a User on our KV INCOME platform who is engaging in behavior that violates the Terms of Service, please contact KV INCOME Here.
    8.    FEEDBACK 8.1 KV INCOME welcomes information and feedback from Users to help improve the quality of the Service. Please refer to the following KV INCOME feedback process:
    (i) Feedback should be provided in writing via email or by using the form. (ii) All anonymous feedback will not be accepted. (iii) Users related to the feedback will be fully notified and given an opportunity to improve the situation. (iv) Unclear and derogatory feedback will not be accepted.
    9.    DISCLAIMER OF LIABILITY 9.1 THE SERVICE IS PROVIDED ON AN "AS IS" BASIS WITHOUT ANY WARRANTIES, CLAIMS, OR REPRESENTATIONS MADE BY KV INCOME REGARDING ANY EXPRESS, IMPLIED, OR MANDATORY ASPECTS OF THE SERVICE, INCLUDING WARRANTIES OF QUALITY, PERFORMANCE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
    10.	CONTRIBUTIONS FROM USERS TO THE SERVICE 10.1 When submitting any Content to KV INCOME, you affirm and warrant that you have all necessary rights and approvals to grant the following rights to KV INCOME. You also acknowledge and agree that you are solely responsible for any content you post or make available on or through the Service, including responsibility for accuracy, reliability, originality, clarity of rights, compliance with laws, and any legal limitations associated with any contributed Content. Hereby, the User grants KV INCOME and its successors a continuous, non-revocable, global, non-exclusive, royalty-free, sublicensable, and transferable right to use, copy, distribute, reproduce, transfer, modify, edit, create derivative works from, publicly display, and perform the contributed Content through or in connection with the Service using any media and through any channels, including for promotional or redistributive purposes of all or any portion of the Service (or derivative products of the Service). The rights you grant us terminate only when you or KV INCOME remove the contributed Content from the Service. You understand that your contribution may be transferred to multiple different systems and may be modified to meet technical requirements.
    10.2 Any Content, materials, information, or ideas that the User posts or transmits through the Service or otherwise transfers to KV INCOME in any form (each form referred to as "Submitted Content") shall not be confidential to KV INCOME and may be disseminated or used by KV INCOME or affiliated companies without any fee or responsibility to the User, for any purpose, including the development, production, and promotion of products. By submitting the Submitted Content to KV INCOME, you acknowledge and agree that KV INCOME and/or third parties may independently develop software, applications, interfaces, products, and modify and enhance software, applications, interfaces, products that are identical or similar to the ideas expressed in your Submitted Content regarding functionality, code, or other characteristics. Therefore, you hereby grant KV INCOME and its successors a continuous, non-revocable, global, non-exclusive, royalty-free, sublicensable, and transferable right to use, copy, distribute, reproduce, transfer, modify, edit, create derivative works from, publicly display, and perform the Submitted Content through or in connection with the Submitted Content using any media and through any channels, including for promotional or redistributive purposes of all or any portion of the Service (or derivative products of the Service). This provision does not apply to personal information that is subject to KV INCOME's privacy policy unless you publicly disclose such information on or through the Service
    11. USER'S AFFIRMATION AND ASSURANCE The User affirms and assures that:
    (a) The User possesses the legal capacity (and, in the case of a minor, has valid consent from a parent or legal guardian) and the rights and abilities necessary to enter into these Terms of Service and to comply with the provisions herein; and
    (b) The User only uses the Service for lawful purposes and in accordance with these Terms of Service, as well as all applicable laws, regulations, standards, directives, guidelines, policies, and regulations.
    12. INDEMNIFICATION You agree to indemnify, defend, and hold harmless KV INCOME, its shareholders, subsidiaries, affiliates, directors, officers, agents, co-branders, or partners, and employees of KV INCOME (collectively referred to as the "Indemnified Party") in connection with any claims, actions, proceedings, and lawsuits, as well as obligations, losses, payments, fines, penalties, costs, and related expenses (including dispute resolution costs) incurred by the Indemnified Party arising from (a) transactions conducted on KV INCOME or disputes related to such transactions (unless KV INCOME or its affiliates are the Sellers in the transaction subject to the complaint), (b) KV INCOME's Guarantee Policy, (c) the organization, operation, management, and/or provision of the Services performed by or on behalf of KV INCOME, (d) the violation or non-compliance with any provisions of these Terms of Service or any referenced policies or guidelines herein, (e) your use or misuse of the Service, or (f) your violation of any laws or any rights of any third party, or (g) any Content posted by the User.
    13. APPLICABLE LAW These Terms of Service shall be governed by and construed in accordance with the laws of USA . Any disputes, controversies, claims, or differences arising out of or in connection with these Terms of Service against or relating to KV INCOME or any Indemnified Party subject to these Terms of Service The language of arbitration shall be ENGLISH.
    14. GENERAL PROVISIONS 14.1 KV INCOME reserves all rights not expressly granted herein.
    14.2 KV INCOME has the right to modify these Terms of Service at any time by posting the revised Terms of Service on KV INCOME. The User's continued use of KV INCOME after the posting of such changes shall constitute the User's acceptance of the modified Terms of Service.
    LEGAL NOTICE: Please send all legal notices to KV INCOME at the following address - Recipient: Infinity Team. I HAVE READ THESE TERMS OF SERVICE AND AGREE TO ALL THE TERMS AND CONDITIONS ABOVE AS WELL AS ANY SUBSEQUENTLY AMENDED TERMS. BY CLICKING THE "SIGN UP" OR "SIGN UP VIA FACEBOOK" BUTTON WHEN REGISTERING TO USE KV INCOME, I UNDERSTAND THAT I AM CREATING AN ELECTRONIC SIGNATURE THAT I UNDERSTAND TO HAVE THE SAME VALUE AND EFFECT AS A SIGNATURE SIGNED BY HAND.
    Updated on JUNE 2, 2023.

</div>


</body>

</html>
